### PR TITLE
Make GitHub detect *.4 as Forth.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Hello,

Please merge this, if you like GitHub to detect your `.4` files as Forth.

Thanks!

### CODE REVIEW

**Comment by martiniturbide** [comment]
Thanks

**Comment by larsbrinkhoff** [comment]
Thank you!

If I may be so bold as to ask a favor, could you also do a push to this repo?
https://github.com/OS2World/DEV-FORTH-Forth-2

It will make GitHub pick up the correct language for the `.4TH` files.

**Comment by martiniturbide** [comment]
Hi Lars. 
I'm still not very handly with GitHub. I can do a "Merge Pull Request" just like a I did with "DEV-FORTH-FORTH32", but I'm not sure what do you want to me to do right now with "DEV-FORTH-Forth-2".

Do I have to do something, or do you want me to accept the Merge once you send it?

Regards

**Comment by larsbrinkhoff** [comment]
I meant that you could do any kind of update to that repository, and do a push.

But I'll be happy to make a separate pull request.

**Pull request merged**
